# Generated by Django 5.1.2 on 2024-10-10 22:13

import django.db.models.deletion
import django_ckeditor_5.fields
import emails.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.JSONField(default=list)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('S', 'Sent'), ('F', 'Failed')], default='P', max_length=1)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('message', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Messaje')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', validators=[emails.validators.validate_file_size, emails.validators.validate_file_extension])),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='EmailGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('slug', models.SlugField()),
                ('users', models.ManyToManyField(blank=True, related_name='email_group_users', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'verbose_name': 'Email Group',
                'verbose_name_plural': 'Email Groups',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='EmailInstant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('message', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('send', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('cc_users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cc_users_instant', to=settings.AUTH_USER_MODEL, verbose_name='CC')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_instant_users', to=settings.AUTH_USER_MODEL, verbose_name='From')),
                ('to_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_groups_instant', to='emails.emailgroup', verbose_name='To group')),
                ('to_users', models.ManyToManyField(blank=True, related_name='to_users_instant', to=settings.AUTH_USER_MODEL, verbose_name='For')),
            ],
            options={
                'verbose_name': 'Instant Email',
                'verbose_name_plural': 'Instant Emails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailMassive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('send', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('cc_users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cc_users', to=settings.AUTH_USER_MODEL, verbose_name='CC')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_users', to=settings.AUTH_USER_MODEL, verbose_name='From')),
                ('to_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_groups', to='emails.emailgroup', verbose_name='To groups')),
                ('to_users', models.ManyToManyField(blank=True, related_name='to_users', to=settings.AUTH_USER_MODEL, verbose_name='to')),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.emailtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Massive Email',
                'verbose_name_plural': 'Massive Emails',
                'ordering': ['-created_at'],
            },
        ),
    ]
