# Generated by Django 5.1.1 on 2024-09-23 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified (EST)'),
        ),
        migrations.CreateModel(
            name='BaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_type', models.CharField(choices=[('C', 'CSV'), ('P', 'Parquet')], default='C', max_length=1)),
                ('base_file', models.FileField(upload_to='api/base_files')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.basescenario')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_type', models.CharField(choices=[('C', 'CSV'), ('P', 'Parquet')], default='C', max_length=1)),
                ('execution_file', models.FileField(upload_to='api/exec_files')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.execution')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_type', models.CharField(choices=[('C', 'CSV'), ('P', 'Parquet')], default='C', max_length=1)),
                ('base_file', models.FileField(upload_to='api/solution_files')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.solution')),
            ],
        ),
    ]
