# Generated by Django 5.1.2 on 2024-11-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_scenario_updated_at_basefile_executionfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Optimization Scenario Name'),
        ),
    ]